docs/DeveloperGuide.md
#33 Added new Use Cases
New use cases include:
- Add person
- Tag person
- Untag person
- List all persons
- Filter persons by tag
- Get help
=> Update DG - Add Use Cases

docs/AboutUs.md, docs/DeveloperGuide.md, docs/UserGuide.md, docs/_markbind/layouts/default.md, docs/package-lock.json
=> Update site-wide settings

docs/DeveloperGuide.md
#36 Added terms that might be important into the Developer Guide glossary section.
=> Update DG - Glossary

src/main/java/seedu/address/logic/commands/TagCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/TagCommandParser.java, src/test/java/seedu/address/logic/commands/TagCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/TagCommandParserTest.java
#53 Implemented command to add tags to contacts as well as relevant tests.
=> Add tag command

docs/DeveloperGuide.md
Based on the new convention agreed with the team regarding the use of contact/person
=> Update use of contact/person in the DG

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/commands/ListTagsCommand.java, src/main/java/seedu/address/logic/commands/TagCommand.java, src/main/java/seedu/address/logic/commands/UntagCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/TagCommandParser.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/tag/ActiveTags.java, src/main/java/seedu/address/model/tag/Tag.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/TagCommandTest.java
#85 Added a new command ListTag to show the user the currently used Tags in their address book
=> Add List tag command

src/main/java/seedu/address/logic/commands/TagCommand.java, src/main/java/seedu/address/logic/parser/TagCommandParser.java, src/main/java/seedu/address/model/tag/Tag.java, src/test/java/seedu/address/logic/commands/TagCommandTest.java, src/test/java/seedu/address/logic/parser/TagCommandParserTest.java, src/test/java/seedu/address/model/tag/TagTest.java
Fixed bug where Tag Command does not show error upon duplicate t/ prefixes
#81 Also added new test cases for Tag, TagCommand and TagCommandParser
=> Fix tag command

src/main/java/seedu/address/logic/commands/ActualClearCommand.java, src/main/java/seedu/address/logic/commands/ClearCommand.java, src/main/java/seedu/address/logic/parser/ActualClearCommandParser.java, src/test/java/seedu/address/logic/commands/ActualClearCommandTest.java, src/test/java/seedu/address/logic/commands/ClearCommandTest.java, src/test/java/seedu/address/logic/parser/ActualClearCommandParserTest.java
Typing in any input other then the character 'y' or the word 'yes' (case-insensitive) will no longer be considered as an exception. New test cases have also been added for better test coverage.
=> Update clear feature 2

src/main/java/seedu/address/logic/commands/UntagCommand.java, src/main/java/seedu/address/logic/parser/UntagCommandParser.java, src/test/java/seedu/address/logic/commands/UntagCommandTest.java, src/test/java/seedu/address/logic/parser/UntagCommandParserTest.java
Untag checks for alphanumeric characters, multiple 't/' occurences, invalid tags and indexes.
=> Enhance error checking for untag

src/main/java/seedu/address/logic/commands/SortCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/person/UniquePersonList.java, src/main/java/seedu/address/ui/HelpWindow.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/SortCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/model/AddressBookTest.java, src/test/java/seedu/address/model/ModelManagerTest.java, src/test/java/seedu/address/model/person/UniquePersonListTest.java
Added sort command and relevant test cases
=> Add sort command

src/main/java/seedu/address/logic/commands/AddWeddingCommand.java, src/main/java/seedu/address/logic/parser/AddWeddingCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/wedding/UniqueWeddingList.java, src/main/java/seedu/address/model/wedding/Wedding.java, src/main/java/seedu/address/model/wedding/WeddingDate.java, src/main/java/seedu/address/model/wedding/WeddingName.java, src/main/java/seedu/address/storage/JsonAdaptedWedding.java, src/test/java/seedu/address/logic/commands/AddWeddingCommandTest.java, src/test/java/seedu/address/logic/parser/AddWeddingCommandParserTest.java, src/test/java/seedu/address/model/AddressBookTest.java, src/test/java/seedu/address/model/wedding/UniqueWeddingListTest.java, src/test/java/seedu/address/model/wedding/WeddingTest.java, src/test/java/seedu/address/testutil/TypicalWeddings.java
1. Added WeddingDate and WeddingName classes
2. Updated related tests/wedding commands
=> Add WeddingDate and WeddingName classes and update related tests/wedding commands

src/main/java/seedu/address/storage/JsonAdaptedWedding.java
Fix date formatting issue which was caused by date strings being saved in standard iso format (dd-mm-yyyy) to the json file instead of the custom dd/mm/yyyy format
=> Fix date formatting issue

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/AssignContactToWeddingCommand.java, src/main/java/seedu/address/logic/commands/UnassignContactFromWeddingCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/logic/parser/UnassignContactFromWeddingCommandParser.java, src/main/java/seedu/address/model/wedding/Wedding.java, src/test/java/seedu/address/logic/commands/UnassignContactFromWeddingCommandTest.java, src/test/java/seedu/address/logic/parser/UnassignContactFromWeddingCommandParserTest.java
Added unassign contact from wedding command with test cases. Changed assign and unassign commands.
=> Add unassign contact command with test cases

src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/Address.java, src/main/java/seedu/address/model/person/Email.java, src/main/java/seedu/address/model/person/Name.java, src/main/java/seedu/address/model/person/Phone.java, src/main/java/seedu/address/model/tag/Tag.java, src/main/resources/view/PersonListCard.fxml, src/test/java/seedu/address/model/person/AddressTest.java, src/test/java/seedu/address/model/person/EmailTest.java, src/test/java/seedu/address/model/person/NameTest.java, src/test/java/seedu/address/model/person/PhoneTest.java
#114 
Fields:
- Name: 40 characters
- Phone: 3 - 15 characters (inclusive)
- Email: 40 characters
- Address: 50 characters
- Tag: 16 characters
=> Implement character limits for Person fields

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/EditWeddingCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/EditWeddingCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/wedding/Wedding.java, src/main/java/seedu/address/model/wedding/WeddingDate.java, src/main/java/seedu/address/model/wedding/WeddingName.java, src/main/java/seedu/address/storage/JsonAdaptedWedding.java, src/test/java/seedu/address/logic/commands/EditWeddingCommandTest.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java, src/test/java/seedu/address/logic/parser/EditWeddingCommandParserTest.java, src/test/java/seedu/address/testutil/EditWeddingDescriptorBuilder.java
=> Implement Edit Wedding feature

src/main/java/seedu/address/logic/commands/AddWeddingCommand.java, src/main/java/seedu/address/logic/parser/AddWeddingCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/test/java/seedu/address/logic/commands/AddWeddingCommandTest.java, src/test/java/seedu/address/logic/parser/AddWeddingCommandParserTest.java, src/test/java/seedu/address/logic/parser/EditWeddingCommandParserTest.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/testutil/TypicalWeddings.java
- Now validates input date is after current date
- Allows users to optionally assign contacts while adding a new wedding
Closes #118
=> Modify addw command

src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/commands/DeleteWeddingCommand.java, src/main/java/seedu/address/logic/commands/EditWeddingCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/DeleteWeddingCommandParser.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/test/java/seedu/address/logic/commands/DeleteWeddingCommandTest.java, src/test/java/seedu/address/logic/parser/DeleteWeddingCommandParserTest.java, src/test/java/seedu/address/testutil/TypicalIndexes.java
Fixes #130 
Added functionality for deleting a wedding via the index
=> Wedding delete feature

src/main/java/seedu/address/logic/Logic.java, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/wedding/WeddingName.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/WeddingCard.java, src/main/java/seedu/address/ui/WeddingListPanel.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/MainWindow.fxml, src/main/resources/view/WeddingCard.fxml, src/main/resources/view/WeddingListPanel.fxml
=> Branch wedding panel UI

src/main/java/seedu/address/ui/HelpWindow.java
=> Update help command for v1.4 feature updates

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/logic/parser/UntagCommandParserTest.java
=> Add validation for duplicate contact assigned to wedding

docs/UserGuide.md, docs/diagrams/BetterModelClassDiagram.puml, docs/package-lock.json, docs/package.json
Addresses #158 
- Updated BetterModelClassDIagram to include Wedding-related classes in the developer guide
- Updated user guide to include `editw` and `deletew` command descriptions
=> Update user guide and developer guide

docs/DeveloperGuide.md, docs/diagrams/UiClassDiagram.puml
=> Update dg UI component diagram

src/main/java/seedu/address/ui/HelpWindow.java
=> Update Help Message to match UG order

src/main/java/seedu/address/logic/parser/ParserUtil.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java
=> Fix related to contacts not specified for addw usage

docs/UserGuide.md, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java
=> Remove date validation for wedding

src/main/java/seedu/address/logic/Logic.java, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/commands/AssignContactToWeddingCommand.java, src/main/java/seedu/address/logic/commands/UnassignContactFromWeddingCommand.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/ui/CurrentWeddingNameCard.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/WeddingListPanel.java, src/main/resources/view/CurrentWeddingNameCard.fxml, src/main/resources/view/WeddingListPanel.fxml, src/test/java/seedu/address/logic/commands/AddCommandTest.java
Updated UI to display wedding name of the wedding the user is currently in. If the user is not in any wedding the text will simply be "Not viewing any wedding".
=> Show current wedding name in WeddingListPanel

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/AssignContactToWeddingCommand.java, src/main/java/seedu/address/logic/commands/UnassignContactFromWeddingCommand.java, src/main/java/seedu/address/logic/parser/UnassignContactFromWeddingCommandParser.java, src/test/java/seedu/address/logic/commands/UnassignContactFromWeddingCommandTest.java, src/test/java/seedu/address/logic/parser/UnassignContactFromWeddingCommandParserTest.java
Modified assign and unassign commands with updated test cases.
User guide also updated.
=> Modify assign and unassign commands

src/main/java/seedu/address/logic/commands/DeleteWeddingCommand.java, src/main/resources/view/CurrentWeddingNameCard.fxml, src/test/java/seedu/address/model/wedding/WeddingDateTest.java, src/test/java/seedu/address/model/wedding/WeddingNameTest.java
Fixes #197, #200
Now when a wedding is deleted while the user is viewing it, it will return to the main list, and the current wedding name view will be updated accordingly.
On a sidenote, test cases for WeddingName are up as well and the background colour for the current wedding name display has been updated
=> Debug delete wedding issues

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/FilterCommand.java, src/main/java/seedu/address/logic/commands/UnassignContactFromWeddingCommand.java, src/test/java/seedu/address/logic/commands/FilterCommandTest.java
=> Update FilterCommand and fix UI issues

src/main/java/seedu/address/logic/parser/UnassignContactFromWeddingCommandParser.java, src/test/java/seedu/address/logic/parser/UnassignContactFromWeddingCommandParserTest.java
Modified error message for unassign command to be clearer, and modified test cases.
=> Small fixes yxshrk

src/main/java/seedu/address/logic/commands/AddWeddingCommand.java, src/main/java/seedu/address/logic/commands/EditWeddingCommand.java, src/main/java/seedu/address/logic/commands/UntagCommand.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/HelpWindow.css
=> Test new fonts

src/main/java/seedu/address/logic/commands/TagCommand.java, src/main/java/seedu/address/logic/commands/UntagCommand.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/tag/Tag.java, src/test/java/seedu/address/model/person/PersonTest.java, src/test/java/seedu/address/model/tag/TagTest.java
=> Implement case-insensitive checks for Tag

docs/DeveloperGuide.md, docs/UserGuide.md, src/main/java/seedu/address/ui/HelpWindow.java
=> Update dg manual testing appendix

docs/DeveloperGuide.md, docs/UserGuide.md, docs/diagrams/BetterModelClassDiagram.puml, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/ClearCommand.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java
Closes #289, #329, #328, #326, #322, #325, #295, #308
=> Update UG, DG and fix the ViewWeddingName issue when adding a new contact

docs/DeveloperGuide.md
=> Update DG User Guides for add, editw and deletew (with tweaks to others)

docs/UserGuide.md
Resolve #324, resolve #303, resolve #293 
Added new glossary section and linked relevant words to the glossary.
Only the first occurrence of a specific term in each section links to the glossary.
=> Add glossary and link relevant text to glossary

docs/DeveloperGuide.md, docs/UserGuide.md
Page breaks, other minor edits for grammar/clarity
=> Update UG & DG again
